services:
  client:
    build:
      context: ./client
      target: production
    container_name: hostyourbot-client-prod
    ports:
      - "80:80"
    environment:
      - NODE_ENV=production
    restart: unless-stopped
