name: Deploy
on:
  push:
    branches:
      - main
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    env:
      REGISTRY: docker.hostyourbot.app
      REGISTRY_USERNAME: admin
      IMAGE_TAG: ${{ github.sha }}
    steps:
      - uses: actions/checkout@v4
      - name: Charger l'environnement
        run: |
          printf "%s\n" "${{ secrets.PROD_ENV_FILE }}" > .env.production
      - uses: docker/setup-buildx-action@v3
      - uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ env.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
      - name: Build and push images
        env:
          IMAGE_TAG: ${{ env.IMAGE_TAG }}
        run: |
          docker buildx build --platform linux/amd64 \
            --build-arg SERVICE_PATH=auth-service \
            --target production \
            -t ${REGISTRY}/hostyourbot/auth-service:${IMAGE_TAG} \
            -f auth-service/Dockerfile \
            --push \
            ./auth-service

          docker buildx build --platform linux/amd64 \
            --build-arg SERVICE_PATH=logs-service \
            --target production \
            -t ${REGISTRY}/hostyourbot/logs-service:${IMAGE_TAG} \
            -f logs-service/Dockerfile \
            --push \
            ./logs-service

          docker buildx build --platform linux/amd64 \
            --build-arg SERVICE_PATH=k8s-service \
            --target production \
            -t ${REGISTRY}/hostyourbot/k8s-service:${IMAGE_TAG} \
            -f k8s-service/Dockerfile \
            --push \
            .

          docker buildx build --platform linux/amd64 \
            --build-arg SERVICE_PATH=mail-service \
            --target production \
            -t ${REGISTRY}/hostyourbot/mail-service:${IMAGE_TAG} \
            -f mail-service/Dockerfile \
            --push \
            ./mail-service

          docker buildx build --platform linux/amd64 \
            --target production \
            -t ${REGISTRY}/hostyourbot/client:${IMAGE_TAG} \
            -f client/Dockerfile \
            --push \
            ./client

          docker buildx build --platform linux/amd64 \
            --build-arg SERVICE_PATH=webhook-service \
            --target production \
            -t ${REGISTRY}/hostyourbot/webhook-service:${IMAGE_TAG} \
            -f webhook-service/Dockerfile \
            --push \
            .
      - name: Tag latest
        run: |
          services="auth-service logs-service k8s-service mail-service client webhook-service"
          for service in $services; do
            docker buildx imagetools create \
              ${REGISTRY}/hostyourbot/${service}:${IMAGE_TAG} \
              --tag ${REGISTRY}/hostyourbot/${service}:latest
          done
      - uses: webfactory/ssh-agent@v0.8.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
      - name: Add known hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts
      - name: Deploy
        env:
          SSH_USER: ${{ secrets.SSH_USER }}
          SSH_HOST: ${{ secrets.SSH_HOST }}
          REGISTRY_PASSWORD: ${{ secrets.REGISTRY_PASSWORD }}
          DEPLOY_PATH: ${{ secrets.DEPLOY_PATH }}
          IMAGE_TAG: ${{ github.sha }}
        run: |
          ssh $SSH_USER@$SSH_HOST "docker login ${REGISTRY} -u ${REGISTRY_USERNAME} -p ${REGISTRY_PASSWORD}"
          ssh $SSH_USER@$SSH_HOST "cd ${DEPLOY_PATH} && git fetch origin && git checkout main && git pull origin main"
          ssh $SSH_USER@$SSH_HOST "cd ${DEPLOY_PATH} && IMAGE_TAG=${IMAGE_TAG} docker compose -f docker-compose.prod.yml pull"
          ssh $SSH_USER@$SSH_HOST "cd ${DEPLOY_PATH} && IMAGE_TAG=${IMAGE_TAG} docker compose -f docker-compose.prod.yml up -d --remove-orphans"
