name: Deploy
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: webfactory/ssh-agent@v0.8.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
      - name: Add known hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts
      - name: Deploy sur VPS
        env:
          SSH_USER: ${{ secrets.SSH_USER }}
          SSH_HOST: ${{ secrets.SSH_HOST }}
          DEPLOY_PATH: ${{ secrets.DEPLOY_PATH }}
          PROD_ENV_FILE: ${{ secrets.PROD_ENV_FILE }}
        run: |
          ssh $SSH_USER@$SSH_HOST "cd ${DEPLOY_PATH} && git fetch origin && git checkout main && git pull origin main"
          ssh $SSH_USER@$SSH_HOST "cd ${DEPLOY_PATH} && docker compose -f docker-compose.prod.yml build"
          ssh $SSH_USER@$SSH_HOST "cd ${DEPLOY_PATH} && docker compose -f docker-compose.prod.yml up -d --remove-orphans"
